# Generated by Django 5.0 on 2023-12-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(default="Hello Everyone", max_length=20),
        ),
    ]
