# Generated by Django 5.0 on 2023-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(default="Hello Everyone", max_length=100),
        ),
    ]
